name: CI for Dotnet core API project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  WEBAPP_NAME: dotnet-core-api
  WEBAPP_PUBLISH_PATH: ./published
  DOTNET_CORE_VERSION: '2.1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish --no-build -output ${{ env.WEBAPP_PUBLISH_PATH }}
