name: CI for Dotnet core API project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
    
env:
  WEBAPP_NAME: dotnet-core-api
  WEBAPP_PUBLISH_PATH: ./published
  DOTNET_CORE_VERSION: '2.1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
        
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ${{ env.WEBAPP_PUBLISH_PATH }}
      
  
